USE [master]
GO

/****** Object:  Database [AmazeKart]    Script Date: 4/19/2023 10:43:48 PM ******/
CREATE DATABASE [AmazeKart]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AmazeKart', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AmazeKart.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AmazeKart_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AmazeKart_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AmazeKart].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AmazeKart] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AmazeKart] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AmazeKart] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AmazeKart] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AmazeKart] SET ARITHABORT OFF 
GO

ALTER DATABASE [AmazeKart] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AmazeKart] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AmazeKart] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AmazeKart] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AmazeKart] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AmazeKart] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AmazeKart] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AmazeKart] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AmazeKart] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AmazeKart] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AmazeKart] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AmazeKart] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AmazeKart] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AmazeKart] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AmazeKart] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AmazeKart] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AmazeKart] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AmazeKart] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AmazeKart] SET  MULTI_USER 
GO

ALTER DATABASE [AmazeKart] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AmazeKart] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AmazeKart] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AmazeKart] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AmazeKart] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AmazeKart] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AmazeKart] SET  READ_WRITE 
GO


